# countries.py

country_names = {
    "de": "Germany",
    "id": "Indonesia",
    "us": "United States",
    "es": "Spain",
    "cz": "Czech Republic",
    "by": "Belarus",
    "uz": "Uzbekistan",
    "my": "Malaysia",
    "sa": "Saudi Arabia",
    "be": "Belgium",
    "ph": "Philippines",
    "za": "South Africa",
    "gb": "United Kingdom",
    "ru": "Russia",
    "fr": "France",
    "cn": "China",
    "ma": "Morocco",
    "ee": "Estonia",
    "no": "Norway",
    "lv": "Latvia",
    "rs": "Serbia",
    "it": "Italy",
    "sg": "Singapore",
    "at": "Austria",
    "fi": "Finland",
    "th": "Thailand",
    "in": "India",
    "tr": "Turkey",
    "mx": "Mexico",
    "pl": "Poland",
    "sc": "Seychelles",
    "tm": "Turkmenistan",
    "kg": "Kyrgyzstan",
    "nl": "Netherlands",
    "il": "Israel",
    "br": "Brazil",
    "jp": "Japan",
    "ca": "Canada",
    "kz": "Kazakhstan",
    "gr": "Greece",
    "ua": "Ukraine",
    "ro": "Romania",
    "si": "Slovenia",
    "au": "Australia",
    "md": "Moldova",
    "tj": "Tajikistan",
    "eg": "Egypt",
    "hk": "Hong Kong",
    "bg": "Bulgaria",
    "kr": "South Korea",
    "cy": "Cyprus",
    "bd": "Bangladesh",
    "ae": "United Arab Emirates",
    "ng": "Nigeria",
    "tw": "Taiwan",
    "lt": "Lithuania",
    "dk": "Denmark",
    "vn": "Vietnam",
    "pt": "Portugal",
    "ge": "Georgia",
    "ie": "Ireland",
    "cl": "Chile",
    "ch": "Switzerland",
    "se": "Sweden",
}
